x = "String world " # string
x = 25 #int
x = 25.04 #float
x = 1j # complex
x = range(-455555,221212126) # range
sasas = ['python','Dart','Java','Dart'] #List ( square brackets) changle order
x = ('python','Dart','Java','Dart') #tuple (parenthis) cannnot change order
sasa = {'python','Dart','Dart','Java'} #set
x =  frozenset({'python','Dart','Java'}) #frozenset
x = {"name":"Sai Gopi",'age':25} #dict {'key':'value'}
x = True | False #bool
x = b'hello' #bytes
x = bytearray(5) #bytearray
x = memoryview(bytes(5)) #memory
